name: foxutils-hud
version: '${project.version}'
main: me.foxils.foxutils.FoxutilsHud
api-version: '1.21'
authors: [Foxils @foxils. on Discord]

depend:
  - foxutils-config

commands:
  debughud:
    description: Enables the debug hud.
    usage: /<command>
    permission: op
  enablehud:
    description: Enables a hud element using its respective configuration key.
    usage: /<command>
    permission: op
  gethuds:
    description: Sends a message containing the names and keys of all currently registered hud configurations.
    usage: /<command>
    permission: op