name: foxutils-hud
version: '${project.version}'
main: me.foxils.foxutils.FoxutilsHud
api-version: '1.21'
authors: [Foxils @foxils. on Discord]

depend:
  - foxutils-config

commands:
  debughud:
    description: show debug hud
    usage: /<command>
    permission: op
  gethuds:
    description: Send message containing the names of all the registered huds.
    usage: /<command>
    permission: op