name: foxutils-items
version: '${project.version}'
main: me.foxils.foxutils.FoxutilsItems
api-version: '1.8.8'

commands:
  getitem:
    description: Get custom item using the item's key
    usage: /<command> <player> <itemkey> <amount>
    permission: op
    aliases: get
  listitems:
    description: Lists all currently registered items
    usage: /<command>
    permission: op